language: ruby
sudo: required
rvm:
  - 2.2.1
services:
  - postgresql
before_script:
  - cp config/database.yml.travis config/database.yml
  - psql -c 'create database travis_ci_test;' -U postgres
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec rake db:test:prepare

script: 
  - bundle exec rspec --exclude-pattern "spec/{routing,views/**}/*_spec.rb"
install: bundle install --jobs=1
cache: bundler